version: '3'

services:
  redis-server:
    image: 'redis'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /visits:/visits
    ports:
      - "8000:8000"
